// Copyright 2011-2013 Renato Tegon Forti

// Distributed under the Boost Software License, Version 1.0.
// See http://www.boost.org/LICENSE_1_0.txt

// Revision History
// 12-05-2012 dd-mm-yyyy - Initial Release

#ifndef BOOST_APPLICATION_APPLICATION_VERSION_HPP
#define BOOST_APPLICATION_APPLICATION_VERSION_HPP

#define BOOST_APPLICATION_VERSION_MAJOR 0
#define BOOST_APPLICATION_VERSION_MINOR 4
#define BOOST_APPLICATION_VERSION_BUILD 1

// major.minor.build

#ifndef BOOST_APPLICATION_VERSION
#define BOOST_APPLICATION_VERSION \
    BOOST_STRINGIZE(BOOST_APPLICATION_VERSION_MAJOR) "." \
    BOOST_STRINGIZE(BOOST_APPLICATION_VERSION_MINOR) "." \
    BOOST_STRINGIZE(BOOST_APPLICATION_VERSION_BUILD)
#endif // BOOST_APPLICATION_VERSION

#endif // BOOST_APPLICATION_APPLICATION_VERSION_HPP

